### ISSUE TITLE
[Roadmap] GenCode Roadmap 2024

### ISSUE THREAD

**Issue by pheeca** [pheeca/GenCode#1]
- [ ] -Add Documentation
- [ ] -Tutorial Video
- [ ] -Detailed blog posts on how to use it
- [ ] -Add in Readme API Keys
- [ ] -Explore image/Vision integration use-cases
- [ ] -Explore Sound integration use-cases
- [ ] -Explore Multimodal
- [ ] -If/Condition support
- [ ] -Add support for Mistral AI, deepinfra
- [ ] open sister projects for npm, pip
